Actualiza los contenedores
IslasGECI/islasgeci.org pull request #17
Opened 2021-02-09 19:23 UTC by xwalls

2021-02-11 17:25 UTC, evaristor requested changes
Aquí va la primer tanda

2021-02-11 17:25 UTC, evaristor commented on src/start_containers
> +# Carga credenciales:t
Creo que esto fue un dedazo:

```suggestion
# Carga credenciales:
```

2021-02-11 17:25 UTC, evaristor commented on src/start_containers
> +docker run --detach --publish 8999:80   --rm islasgeci/kata_flbc_jxavierpp
Vamos indicando la versión:

```suggestion
docker run --detach --publish 8999:80   --rm islasgeci/kata_flbc_jxavierpp:latest
```

2021-02-11 17:25 UTC, evaristor commented on src/start_containers
>  docker pull mysql:8
Faltó hecer _pull_ a `islasgeci/islas.org.mx` y a `islasgeci/kata_flbc_jxavierpp`

2021-02-11 17:25 UTC, evaristor commented on src/start_containers
> +docker run --detach --publish 3307:3307 --rm --volume islas_mysql_db_data:/var/lib/mysql --name islas_mysql_db --env-file /home/ciencia_datos/.env mysql:8.0 --default-authentication-plugin=mysql_nati
Creo que ya creció mucho este _scritp_ y esta instrucción es bastante distinta al resto. Vamos ordenando alfabéticamente las opciones aunque ya no quede ordenado por puerto:

```suggestion
docker run --detach --env-file /home/ciencia_datos/.env --name islas_mysql_db --publish 3307:3307 --rm --volume islas_mysql_db_data:/var/lib/mysql mysql:8.0 --default-authentication-plugin=mysql_native_password
```

2021-02-11 17:25 UTC, evaristor commented on src/start_containers
> +docker run --detach --publish 8081:80   --rm --link islas_mysql_db:mysql --env-file /home/ciencia_datos/.env islasgeci/islas.org.mx
Creo que ya creció mucho este scritp y esta instrucción es bastante distinta al resto. Vamos ordenando alfabéticamente las opciones aunque ya no quede ordenado por puerto:

```suggestion
docker run --detach --env-file /home/ciencia_datos/.env --link islas_mysql_db:mysql --publish 8081:80 --rm islasgeci/islas.org.mx
```

2021-02-15 20:36 UTC, xwalls commented on src/start_containers
> +docker run --detach --publish 8999:80   --rm islasgeci/kata_flbc_jxavierpp
gracias, acepto tu sugerencia

2021-02-15 20:39 UTC, xwalls commented on src/start_containers
>  docker pull mysql:8
lo agregare ahora mismo, gracias @evaristor

2021-02-15 20:45 UTC, xwalls commented on src/start_containers
> +docker run --detach --publish 8999:80   --rm islasgeci/kata_flbc_jxavierpp
no me permitió directamente hacerlo desde aquí, 
pero lo pude hacer desde mi local.
Gracias @evaristor!

2021-02-15 20:45 UTC, xwalls commented on src/start_containers
>  docker pull mysql:8
listo.

2021-02-16 23:25 UTC, xwalls commented
Tuvimos un Tritomate (MB,FR,XP) donde revisamos cada instrucción nueva en el servidor, encontramos que no estaba construida la imagen de la kata de xavier en docker hub para que pudiera correr, 
`
docker pull islasgeci/kata_flbc_jxavierpp:latest
`
`
docker run --detach --publish 8999:80   --rm islasgeci/kata_flbc_jxavierpp:latest
`
La construimos y la mandamos a docker hub para después probar las instrucciones con éxito.

2021-02-16 23:28 UTC, merged